apiVersion: v1
kind: Service
metadata:
  name: lua-ms
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: lua-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lua-ms
spec:
  selector:
    matchLabels:
      app: lua-ms
  template:
    metadata:
      labels:
        app: lua-ms
    spec:
      containers:
      - image: docker.io/hectorvido/lua-app:latest
        name: lua-ms
        env:
        - name: DB_HOST
          value: mariadb.default.svc.cluster.local
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: lua
        - name: DB_PASSWORD
          value: 4linux
        - name: DB_DATABASE
          value: lua
        ports:
        - containerPort: 80
          name: http
