apiVersion: v1
kind: Service
metadata:
  name: lua-ms-{{ .Release.Name }}
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: lua-ms-{{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lua-ms-{{ .Release.Name }}
spec:
  replicas: 20
  selector:
    matchLabels:
      app: lua-ms-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: lua-ms-{{ .Release.Name }}
    spec:
      containers:
      - image: docker.io/hectorvido/lua-app:latest
        name: lua-ms-{{ .Release.Name }}
        env:
        - name: DB_HOST
          value: "{{ .Values.DB_HOST }}"   #mariadb.default.svc.cluster.local
        - name: DB_PORT
          value: "{{ .Values.DB_PORT }}" #3306"
        - name: DB_USER
          value: "{{ .Values.DB_USER }}" #lua
        - name: DB_PASSWORD
          value: "{{ .Values.DB_PASSWORD}}" #4linux
        - name: DB_DATABASE
          value: "{{ .Values.DB_DATABASE }}" #lua
        ports:
        - containerPort: 80
          name: http
