apiVersion: v1
kind: Service
metadata:
  name: mariadb-{{ .Release.Name }}
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb-{{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: mariadb-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: mariadb-{{ .Release.Name }}
    spec:
      containers:
      - image: mariadb:10
        name: mariadb-{{ .Release.Name }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: lua
        - name: MYSQL_PASSWORD
          value: 4linux
        - name: MYSQL_DATABASE
          value: lua
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage-{{ .Release.Name }}
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage-{{ .Release.Name }}
        persistentVolumeClaim:
          claimName: mariadb-pv-claim-{{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
